[versions]
agp = "8.12.3"
kotlin = "2.2.20"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.09.00"

datastore = "1.1.7"

hilt_v = "2.57.1"
hilt-compose_v = "1.3.0"
retrofit_v = "3.0.0"
logging_v = "4.9.3"
moshi_v = "1.15.2"
navigation_v = "2.9.4"
ksp-version = "2.2.20-2.0.4"

googlemap = "6.12.1"
googlemap_compose = "19.2.0"
googlemap_foundation = "1.9.4"
googlemap_utils = "3.19.0"
googlemap_widgets = "6.12.1"
googlemap_compose_utils = "6.12.1"

room = "2.8.3"
lifecycle = "2.9.4"

androidxJunit = "1.1.5"
espressoCoreVersion = "3.5.1"
ksp = "2.3.1"
hilt = "2.57.2"

materialIconsExtended = "1.7.8"
navigation = "2.9.6"
moshi = "1.15.2"
retrofit = "3.0.0"
coil = "2.7.0"
timber = "5.0.1"

hiltNavigationCompose = "1.3.0"

uiTestJunit4 = "1.9.4"

camerax-version = "1.4.0"
objectDetection = "17.0.2"
tflite = "2.3.0"

imageLabelingCustomCommon = "17.0.0"
imageLabelingDefaultCommon = "17.0.0"
imagelabelling = "17.0.9"
imageodml = "1.0.0-beta1"

appintro = "6.1.0"
coreSplashscreen = "1.0.1"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt_v" }
hilt-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-compose_v" }
hilt-kapt = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt_v" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit_v" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit_v" }
retrofit-okhtt3 = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging_v" }

navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation_v" }
navigation-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation_v" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation_v" }


moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi_v" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi_v" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi_v" }

room-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "room" }
room-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "room" }

room-ktx = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler-kapt = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

googlemap = { group = "com.google.maps.android", name = "maps-compose", version.ref = "googlemap" }
googlemap-compose = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "googlemap_compose" }
googlemap-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "googlemap_foundation" }

lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }

googlemap_utils = { group = "com.google.maps.android", name = "android-maps-utils", version.ref = "googlemap_utils" }
googlemap_widgets = { group = "com.google.maps.android", name = "maps-compose-widgets", version.ref = "googlemap_widgets" }
googlemap_compose_utils = { group = "com.google.maps.android", name = "maps-compose-utils", version.ref = "googlemap_compose_utils" }

androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "uiTestJunit4" }

datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastore" }
datastore-prefs = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }

androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }


camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camerax-version" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax-version" }
camera-lifecyvle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax-version" }
camera-video = { group = "androidx.camera", name = "camera-video", version.ref = "camerax-version" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax-version" }
camera-extensions = { group = "androidx.camera", name = "camera-extensions", version.ref = "camerax-version" }
objectdetection = { group = "com.google.mlkit", name = "object-detection", version.ref = "objectDetection" }
objectdetection-custom = { group = "com.google.mlkit", name = "object-detection-custom", version.ref = "objectDetection" }

tflite = { group = "org.tensorflow", name = "tensorflow-lite", version.ref = "tflite" }
image-labeling-custom-common = { group = "com.google.mlkit", name = "image-labeling-custom-common", version.ref = "imageLabelingCustomCommon" }
image-labeling-default-common = { group = "com.google.mlkit", name = "image-labeling-default-common", version.ref = "imageLabelingDefaultCommon" }
linkfirebase = { group = "com.google.mlkit", name = "linkfirebase", version.ref = "imageLabelingDefaultCommon" }

image-labeling = { group = "com.google.mlkit", name = "image-labeling", version.ref = "imagelabelling" }
image-labeling-custom = { group = "com.google.mlkit", name = "image-labeling-custom", version.ref = "imageLabelingCustomCommon" }

image-odml = { group = "com.google.android.odml", name = "image", version.ref = "imageodml" }

appintro = { group = "com.github.AppIntro", name = "AppIntro", version.ref = "appintro" }

androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt_v" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }



